# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ["localhost:9093"]
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
    - "rules_prometheus.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]
        labels:
          hostname: "MON-server-Prometheus"

  - job_name: "node_exporter"

    static_configs:
      - targets: ["localhost:9100"]
        labels:
          hostname: "MON-server-Node_exporter"
      - targets: ["171.33.122.57:9100"]
        labels:
          hostname: "LAB-server-Node_exporter"
      - targets: ["171.33.121.29:9100"]
        labels:
          hostname: "SQL-server-Node_exporter"
      - targets: ["171.33.89.178:9100"]
        labels:
          hostname: "WP-server-Node_exporter"
      - targets: ["171.33.119.249:9100"]
        labels:
          hostname: "WP2-server-Node_exporter"
      - targets: ["148.253.117.165:9100"]
        labels:
          hostname: "HAP-server-Node_exporter"
      - targets: ["80.247.4.162:9100"]
        labels:
          hostname: "SQL2-server-Node_exporter"
      - targets: ["217.75.167.32:9100"]
        labels:
          hostname: "DOC-server-Node_exporter"

  - job_name: "alertmanager"

    static_configs:
      - targets: ["localhost:9093"]
        labels:
          hostname: "MON-server-Alertmanager"
